/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['compat/indexof.js']) {
  _$jscoverage['compat/indexof.js'] = [];
  _$jscoverage['compat/indexof.js'][6] = 0;
  _$jscoverage['compat/indexof.js'][7] = 0;
  _$jscoverage['compat/indexof.js'][8] = 0;
  _$jscoverage['compat/indexof.js'][9] = 0;
  _$jscoverage['compat/indexof.js'][10] = 0;
  _$jscoverage['compat/indexof.js'][12] = 0;
  _$jscoverage['compat/indexof.js'][13] = 0;
  _$jscoverage['compat/indexof.js'][14] = 0;
  _$jscoverage['compat/indexof.js'][15] = 0;
  _$jscoverage['compat/indexof.js'][17] = 0;
  _$jscoverage['compat/indexof.js'][18] = 0;
  _$jscoverage['compat/indexof.js'][19] = 0;
  _$jscoverage['compat/indexof.js'][20] = 0;
  _$jscoverage['compat/indexof.js'][21] = 0;
  _$jscoverage['compat/indexof.js'][22] = 0;
  _$jscoverage['compat/indexof.js'][23] = 0;
  _$jscoverage['compat/indexof.js'][26] = 0;
  _$jscoverage['compat/indexof.js'][27] = 0;
  _$jscoverage['compat/indexof.js'][29] = 0;
  _$jscoverage['compat/indexof.js'][30] = 0;
  _$jscoverage['compat/indexof.js'][31] = 0;
  _$jscoverage['compat/indexof.js'][32] = 0;
  _$jscoverage['compat/indexof.js'][35] = 0;
}
_$jscoverage['compat/indexof.js'].source = ["// indexOf compares searchElement to elements of the Array using strict","// equality (the same method used by the ===, or triple-equals, operator).","//","// https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Array/indexOf","//","if (!Array.prototype.indexOf) {","    Array.prototype.indexOf = function (searchElement /*, fromIndex */ ) {","        \"use strict\";","        if (this == null) {","            throw new TypeError();","        }","        var t = Object(this);","        var len = t.length &gt;&gt;&gt; 0;","        if (len === 0) {","            return -1;","        }","        var n = 0;","        if (arguments.length &gt; 1) {","            n = Number(arguments[1]);","            if (n != n) { // shortcut for verifying if it's NaN","                n = 0;","            } else if (n != 0 &amp;&amp; n != Infinity &amp;&amp; n != -Infinity) {","                n = (n &gt; 0 || -1) * Math.floor(Math.abs(n));","            }","        }","        if (n &gt;= len) {","            return -1;","        }","        var k = n &gt;= 0 ? n : Math.max(len - Math.abs(n), 0);","        for (; k &lt; len; k++) {","            if (k in t &amp;&amp; t[k] === searchElement) {","                return k;","            }","        }","        return -1;","    }","}"];
_$jscoverage['compat/indexof.js'][6]++;
if ((! Array.prototype.indexOf)) {
  _$jscoverage['compat/indexof.js'][7]++;
  Array.prototype.indexOf = (function (searchElement) {
  _$jscoverage['compat/indexof.js'][8]++;
  "use strict";
  _$jscoverage['compat/indexof.js'][9]++;
  if ((this == null)) {
    _$jscoverage['compat/indexof.js'][10]++;
    throw new TypeError();
  }
  _$jscoverage['compat/indexof.js'][12]++;
  var t = Object(this);
  _$jscoverage['compat/indexof.js'][13]++;
  var len = (t.length >>> 0);
  _$jscoverage['compat/indexof.js'][14]++;
  if ((len === 0)) {
    _$jscoverage['compat/indexof.js'][15]++;
    return -1;
  }
  _$jscoverage['compat/indexof.js'][17]++;
  var n = 0;
  _$jscoverage['compat/indexof.js'][18]++;
  if ((arguments.length > 1)) {
    _$jscoverage['compat/indexof.js'][19]++;
    n = Number(arguments[1]);
    _$jscoverage['compat/indexof.js'][20]++;
    if ((n != n)) {
      _$jscoverage['compat/indexof.js'][21]++;
      n = 0;
    }
    else {
      _$jscoverage['compat/indexof.js'][22]++;
      if (((n != 0) && (n != Infinity) && (n != (- Infinity)))) {
        _$jscoverage['compat/indexof.js'][23]++;
        n = (((n > 0) || -1) * Math.floor(Math.abs(n)));
      }
    }
  }
  _$jscoverage['compat/indexof.js'][26]++;
  if ((n >= len)) {
    _$jscoverage['compat/indexof.js'][27]++;
    return -1;
  }
  _$jscoverage['compat/indexof.js'][29]++;
  var k = ((n >= 0)? n: Math.max((len - Math.abs(n)), 0));
  _$jscoverage['compat/indexof.js'][30]++;
  for (; (k < len); (k++)) {
    _$jscoverage['compat/indexof.js'][31]++;
    if (((k in t) && (t[k] === searchElement))) {
      _$jscoverage['compat/indexof.js'][32]++;
      return k;
    }
}
  _$jscoverage['compat/indexof.js'][35]++;
  return -1;
});
}
