/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['compat/trim.js']) {
  _$jscoverage['compat/trim.js'] = [];
  _$jscoverage['compat/trim.js'][6] = 0;
  _$jscoverage['compat/trim.js'][7] = 0;
  _$jscoverage['compat/trim.js'][8] = 0;
}
_$jscoverage['compat/trim.js'].source = ["// The trim method returns the string stripped of whitespace from both ends.","// trim does not affect the value of the string itself.","//","// https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/String/Trim","//","if(!String.prototype.trim) {","  String.prototype.trim = function () {","    return this.replace(/^\\s+|\\s+$/g,'');","  };","}"];
_$jscoverage['compat/trim.js'][6]++;
if ((! String.prototype.trim)) {
  _$jscoverage['compat/trim.js'][7]++;
  String.prototype.trim = (function () {
  _$jscoverage['compat/trim.js'][8]++;
  return this.replace(/^\s+|\s+$/g, "");
});
}
