/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['core/setinterval.js']) {
  _$jscoverage['core/setinterval.js'] = [];
  _$jscoverage['core/setinterval.js'][13] = 0;
  _$jscoverage['core/setinterval.js'][15] = 0;
  _$jscoverage['core/setinterval.js'][22] = 0;
  _$jscoverage['core/setinterval.js'][23] = 0;
  _$jscoverage['core/setinterval.js'][24] = 0;
  _$jscoverage['core/setinterval.js'][25] = 0;
  _$jscoverage['core/setinterval.js'][29] = 0;
  _$jscoverage['core/setinterval.js'][35] = 0;
  _$jscoverage['core/setinterval.js'][36] = 0;
}
_$jscoverage['core/setinterval.js'].source = ["/**","* Set Interval","* (c) 2013 Bill, BunKat LLC.","*","* Works similar to setInterval() but allows you to specify a Later schedule","* instead of milliseconds.","*","* Later is freely distributable under the MIT license.","* For all details and documentation:","*     http://github.com/bunkat/later","*/","","later.setInterval = function(fn, sched) {","","  var t = later.setTimeout(scheduleTimeout, sched),","      done = false;","","  /**","  * Executes the specified function and then sets the timeout for the next","  * interval.","  */","  function scheduleTimeout() {","    if(!done) {","      fn();","      t = later.setTimeout(scheduleTimeout, sched);","    }","  }","","  return {","","    /**","    * Clears the timeout.","    */","    clear: function() {","      done = true;","      t.clear();","    }","","  };","","};"];
_$jscoverage['core/setinterval.js'][13]++;
later.setInterval = (function (fn, sched) {
  _$jscoverage['core/setinterval.js'][15]++;
  var t = later.setTimeout(scheduleTimeout, sched), done = false;
  _$jscoverage['core/setinterval.js'][22]++;
  function scheduleTimeout() {
    _$jscoverage['core/setinterval.js'][23]++;
    if ((! done)) {
      _$jscoverage['core/setinterval.js'][24]++;
      fn();
      _$jscoverage['core/setinterval.js'][25]++;
      t = later.setTimeout(scheduleTimeout, sched);
    }
}
  _$jscoverage['core/setinterval.js'][29]++;
  return ({clear: (function () {
  _$jscoverage['core/setinterval.js'][35]++;
  done = true;
  _$jscoverage['core/setinterval.js'][36]++;
  t.clear();
})});
});
