/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['date/constant.js']) {
  _$jscoverage['date/constant.js'] = [];
  _$jscoverage['date/constant.js'][13] = 0;
  _$jscoverage['date/constant.js'][14] = 0;
  _$jscoverage['date/constant.js'][15] = 0;
  _$jscoverage['date/constant.js'][16] = 0;
  _$jscoverage['date/constant.js'][17] = 0;
}
_$jscoverage['date/constant.js'].source = ["/**","* Date Constants","* (c) 2013 Bill, BunKat LLC.","*","* Useful constants for dealing with time conversions.","*","* Later is freely distributable under the MIT license.","* For all details and documentation:","*     http://github.com/bunkat/later","*/","","// Time to milliseconds conversion","later.SEC = 1000;","later.MIN = later.SEC * 60;","later.HOUR = later.MIN * 60;","later.DAY = later.HOUR * 24;","later.WEEK = later.DAY * 7;"];
_$jscoverage['date/constant.js'][13]++;
later.SEC = 1000;
_$jscoverage['date/constant.js'][14]++;
later.MIN = (later.SEC * 60);
_$jscoverage['date/constant.js'][15]++;
later.HOUR = (later.MIN * 60);
_$jscoverage['date/constant.js'][16]++;
later.DAY = (later.HOUR * 24);
_$jscoverage['date/constant.js'][17]++;
later.WEEK = (later.DAY * 7);
