/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['array/maxindex.js']) {
  _$jscoverage['array/maxindex.js'] = [];
  _$jscoverage['array/maxindex.js'][3] = 0;
  _$jscoverage['array/maxindex.js'][4] = 0;
  _$jscoverage['array/maxindex.js'][7] = 0;
  _$jscoverage['array/maxindex.js'][8] = 0;
  _$jscoverage['array/maxindex.js'][9] = 0;
  _$jscoverage['array/maxindex.js'][10] = 0;
  _$jscoverage['array/maxindex.js'][14] = 0;
}
_$jscoverage['array/maxindex.js'].source = ["","","later.array.maxIndex = function(arr) {","  var max = arr[0],","      maxIdx = 0;","","  for(var i = 1; i &lt; arr.length; i++) {","    if(arr[i] &gt; max) {","      max = arr[i];","      maxIdx = i;","    }","  }","","  return maxIdx;","};"];
_$jscoverage['array/maxindex.js'][3]++;
later.array.maxIndex = (function (arr) {
  _$jscoverage['array/maxindex.js'][4]++;
  var max = arr[0], maxIdx = 0;
  _$jscoverage['array/maxindex.js'][7]++;
  for (var i = 1; (i < arr.length); (i++)) {
    _$jscoverage['array/maxindex.js'][8]++;
    if ((arr[i] > max)) {
      _$jscoverage['array/maxindex.js'][9]++;
      max = arr[i];
      _$jscoverage['array/maxindex.js'][10]++;
      maxIdx = i;
    }
}
  _$jscoverage['array/maxindex.js'][14]++;
  return maxIdx;
});
