/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['array/minindex.js']) {
  _$jscoverage['array/minindex.js'] = [];
  _$jscoverage['array/minindex.js'][3] = 0;
  _$jscoverage['array/minindex.js'][4] = 0;
  _$jscoverage['array/minindex.js'][7] = 0;
  _$jscoverage['array/minindex.js'][8] = 0;
  _$jscoverage['array/minindex.js'][9] = 0;
  _$jscoverage['array/minindex.js'][10] = 0;
  _$jscoverage['array/minindex.js'][14] = 0;
}
_$jscoverage['array/minindex.js'].source = ["","","later.array.minIndex = function(arr) {","  var min = arr[0],","      minIdx = 0;","","  for(var i = 1; i &lt; arr.length; i++) {","    if(arr[i] &lt; min) {","      min = arr[i];","      minIdx = i;","    }","  }","","  return minIdx;","};"];
_$jscoverage['array/minindex.js'][3]++;
later.array.minIndex = (function (arr) {
  _$jscoverage['array/minindex.js'][4]++;
  var min = arr[0], minIdx = 0;
  _$jscoverage['array/minindex.js'][7]++;
  for (var i = 1; (i < arr.length); (i++)) {
    _$jscoverage['array/minindex.js'][8]++;
    if ((arr[i] < min)) {
      _$jscoverage['array/minindex.js'][9]++;
      min = arr[i];
      _$jscoverage['array/minindex.js'][10]++;
      minIdx = i;
    }
}
  _$jscoverage['array/minindex.js'][14]++;
  return minIdx;
});
