/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['array/next.js']) {
  _$jscoverage['array/next.js'] = [];
  _$jscoverage['array/next.js'][13] = 0;
  _$jscoverage['array/next.js'][15] = 0;
  _$jscoverage['array/next.js'][19] = 0;
  _$jscoverage['array/next.js'][20] = 0;
  _$jscoverage['array/next.js'][22] = 0;
  _$jscoverage['array/next.js'][23] = 0;
  _$jscoverage['array/next.js'][26] = 0;
  _$jscoverage['array/next.js'][27] = 0;
  _$jscoverage['array/next.js'][28] = 0;
  _$jscoverage['array/next.js'][31] = 0;
  _$jscoverage['array/next.js'][34] = 0;
}
_$jscoverage['array/next.js'].source = ["/**","* Next","* (c) 2013 Bill, BunKat LLC.","*","* Returns the next valid value in a range of values, wrapping as needed. Assumes","* the array has already been sorted.","*","* Later is freely distributable under the MIT license.","* For all details and documentation:","*     http://github.com/bunkat/later","*/","","later.array.next = function (val, values, extent) {","","  var cur,","      zeroIsLargest = extent[0] !== 0,","      nextIdx = 0;","","  for(var i = values.length-1; i &gt; -1; --i) {","    cur = values[i];","","    if(cur === val) {","      return cur;","    }","","    if(cur &gt; val || (cur === 0 &amp;&amp; zeroIsLargest &amp;&amp; extent[1] &gt; val)) {","      nextIdx = i;","      continue;","    }","","    break;","  }","","  return values[nextIdx];","};"];
_$jscoverage['array/next.js'][13]++;
later.array.next = (function (val, values, extent) {
  _$jscoverage['array/next.js'][15]++;
  var cur, zeroIsLargest = (extent[0] !== 0), nextIdx = 0;
  _$jscoverage['array/next.js'][19]++;
  for (var i = (values.length - 1); (i > -1); (--i)) {
    _$jscoverage['array/next.js'][20]++;
    cur = values[i];
    _$jscoverage['array/next.js'][22]++;
    if ((cur === val)) {
      _$jscoverage['array/next.js'][23]++;
      return cur;
    }
    _$jscoverage['array/next.js'][26]++;
    if (((cur > val) || ((cur === 0) && zeroIsLargest && (extent[1] > val)))) {
      _$jscoverage['array/next.js'][27]++;
      nextIdx = i;
      _$jscoverage['array/next.js'][28]++;
      continue;
    }
    _$jscoverage['array/next.js'][31]++;
    break;
}
  _$jscoverage['array/next.js'][34]++;
  return values[nextIdx];
});
