/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['array/next.js']) {
  _$jscoverage['array/next.js'] = [];
  _$jscoverage['array/next.js'][13] = 0;
  _$jscoverage['array/next.js'][18] = 0;
  _$jscoverage['array/next.js'][22] = 0;
  _$jscoverage['array/next.js'][23] = 0;
  _$jscoverage['array/next.js'][25] = 0;
  _$jscoverage['array/next.js'][26] = 0;
  _$jscoverage['array/next.js'][27] = 0;
  _$jscoverage['array/next.js'][30] = 0;
  _$jscoverage['array/next.js'][31] = 0;
  _$jscoverage['array/next.js'][34] = 0;
  _$jscoverage['array/next.js'][37] = 0;
}
_$jscoverage['array/next.js'].source = ["/**","* Next","* (c) 2013 Bill, BunKat LLC.","*","* Returns the next valid value in a range of values, wrapping as needed. Assumes","* the array has already been sorted.","*","* Later is freely distributable under the MIT license.","* For all details and documentation:","*     http://github.com/bunkat/later","*/","","later.array.next = function (val, values, extent) {","","  // skip UNDEFINED values...","","","  var cur,","      zeroVal = extent[0] === 0 ? 0 : extent[1],","      next = values[0] || zeroVal;","","  for(var i = values.length-1; i &gt; -1; --i) {","    cur = values[i] || zeroVal;","","    if(cur &gt; val) {","      next = cur;","      continue;","    }","","    if(cur === val) {","      return cur;","    }","","    break;","  }","","  return next &lt;= extent[1] ? next : values[0] || zeroVal;","};"];
_$jscoverage['array/next.js'][13]++;
later.array.next = (function (val, values, extent) {
  _$jscoverage['array/next.js'][18]++;
  var cur, zeroVal = ((extent[0] === 0)? 0: extent[1]), next = (values[0] || zeroVal);
  _$jscoverage['array/next.js'][22]++;
  for (var i = (values.length - 1); (i > -1); (--i)) {
    _$jscoverage['array/next.js'][23]++;
    cur = (values[i] || zeroVal);
    _$jscoverage['array/next.js'][25]++;
    if ((cur > val)) {
      _$jscoverage['array/next.js'][26]++;
      next = cur;
      _$jscoverage['array/next.js'][27]++;
      continue;
    }
    _$jscoverage['array/next.js'][30]++;
    if ((cur === val)) {
      _$jscoverage['array/next.js'][31]++;
      return cur;
    }
    _$jscoverage['array/next.js'][34]++;
    break;
}
  _$jscoverage['array/next.js'][37]++;
  return ((next <= extent[1])? next: (values[0] || zeroVal));
});
